<a href="https://colab.research.google.com/github/ShaamNatheshwar/deep_learning/blob/main/1)introduction_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

create tensors

In [3]:
# assign the variable , use tf.Variable mention wat is the string and string type
# these above stuffs have an value of 1 so simply a scaler
#the rank will be literally zero 
variable = tf.Variable("This is a string", tf.string)

In [ ]:
variable

In [4]:
number = tf.Variable(324,tf.int16)

In [5]:
# ranks
# here we are using array , the array has a value of 1 , we can increase the rank by nesting more stuffs,make sure tht we use
# 2 brackets
rank_1 = tf.Variable(["shaam","sss"],tf.string)

In [6]:
tf.rank(rank_1)
# we should have same number of elements

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
rank_2 = tf.Variable([["ssn","sss"],["vvp","ssg"]],tf.string)

In [8]:
# here the numpy2 gives the rank
tf.rank(rank_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### **shape**

In [9]:
# .shape helps in giving the shape this implies tht there 2 elements in first and second
rank_2.shape

TensorShape([2, 2])

In [10]:
# this 1,2,3 shows tht ... I need an overall of 1 within tht it should have 2 list with 3 elements respectively on it
tensor_1 = tf.ones([1,2,3])
tensor_1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [11]:
tensor_2 = tf.reshape(tensor_1,[3,2,1])
tensor_2

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [13]:
# This negative term
tensor_3 = tf.reshape(tensor_2,[3,-1])
tensor_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

different types of tensors
 
variables

constant

place holders

sparse tensors¶

In [14]:
# note tht except variable all are immutable

In [15]:
# sometimes while working we need to evaluate tensor like say we have to get its values so for tht we will be using this method

In [16]:
with tf.Session() as sess:
    tensor.eval()

AttributeError: ignored